### ISSUE TITLE
first pod will not start mysql 

### ISSUE THREAD

**Issue by HBO2** [paulczar/k8s-percona-xtradb-cluster#2]
Hi, 
I am not sure I can bother you, but when using the official Helm chart I get this error. Did a search everywhere, but seems I am the only one :-(
```
2018-04-12 20:17:12 0 [Warning] Using unique option prefix key_buffer instead of key_buffer_size is deprecated and will be removed in a future release. Please use the full name instead.
2018-04-12 20:17:12 0 [Warning] TIMESTAMP with implicit DEFAULT value is deprecated. Please use --explicit_defaults_for_timestamp server option (see documentation for more details).
2018-04-12 20:17:12 0 [Note] mysqld (mysqld 5.6.38-83.0-56) starting as process 14 ...
2018-04-12 20:17:12 14 [ERROR] Fatal error: Please read "Security" section of the manual to find out how to run mysqld as root!
2018-04-12 20:17:12 14 [ERROR] Aborting
2018-04-12 20:17:12 14 [Note] Binlog end
2018-04-12 20:17:12 14 [Note] mysqld: Shutdown complete
```

i am using this values.yaml:
```
# Default values for Percona XtraDB Cluster

## percona image and version
## ref: https://hub.docker.com/r/percona/percona-xtradb-cluster/tags/
image:
  repository: "percona/percona-xtradb-cluster"
  tag: "5.6.38"
  pullPolicy: IfNotPresent

# Desired number of members of xtradb cluster
replicas: 3

## Specify password for root user
##
# mysqlRootPassword: not-a-secure-password

## Specify password for xtradb backup user
##
xtraBackupPassword: replicate-ain

## Uncomment to create a database user
##
mysqlUser: test
mysqlPassword: test21

## Allow unauthenticated access, uncomment to enable
##
# mysqlAllowEmptyPassword: true

## Uncomment to Create a database
##
mysqlDatabase: test

## Persist data to a persitent volume
persistence:
  enabled: true
  ## percona data Persistent Volume Storage Class
  ## If defined, storageClassName: <storageClass>
  ## If set to "-", storageClassName: "", which disables dynamic provisioning
  ## If undefined (the default) or set to null, no storageClassName spec is
  ##   set, choosing the default provisioner.  (gp2 on AWS, standard on
  ##   GKE, AWS & OpenStack)
  ##
  storageClass: "rook-block"
  accessMode: ReadWriteOnce
  size: 8Gi

## Configure resource requests and limits
## ref: http://kubernetes.io/docs/user-guide/compute-resources/
##
resources:
  requests:
    memory: 500Mi
    cpu: 200m

configFiles:
  node.cnf: |+
    [mysqld]
    datadir=/var/lib/mysql
    default_storage_engine=InnoDB
    binlog_format=ROW
    innodb_flush_log_at_trx_commit  = 0
    innodb_flush_method             = O_DIRECT
    innodb_file_per_table           = 1
    innodb_autoinc_lock_mode=2
    bind_address = 0.0.0.0
    wsrep_slave_threads=2
    wsrep_cluster_address=gcomm://
    wsrep_provider=/usr/lib/galera3/libgalera_smm.so
    wsrep_cluster_name=galera
    wsrep_sst_method=xtrabackup-v2

## When set to true will create sidecar for `prom/mysqld-exporter`
## metrics exporting
metricsExporter: false

## When set to true will create sidecar to tail mysql log
# logTail: true


```
